### ISSUE TITLE
Large numbers cause crashes

### ISSUE THREAD

**Issue by EthanHalliday** [Hat-Maketh-Man/Dungeon-Master#1]
Yields NumberFormatException. Limits should be added to prevent this

**Comment by Hat-Maketh-Man** [comment]
Large numbers of what? Level? Worth?

**Comment by EthanHalliday** [comment]
All non-name fields are causing it

**Comment by Hat-Maketh-Man** [comment]
I guessed so; I'm updating the event-handler to check the length of the text in the TextField's under ItemPane such that any number input has to be less than 3 characters in length (as maximum values for the items will be limited to 999).
